name: Expression Demo

on:
  push:
    branches:
      - main

jobs:
  expression-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print message based on branch name
        if: contains(github.ref, 'main')
        run: echo "This is the main branch."
      - name: Print message if push was a tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "A tag was pushed."
      - name: Print message if event was a pull request
        if: github.event_name == 'pull_request'
        run: echo "This was a pull request event."
      - name: Print message if commit message contains keyword
        if: contains(github.event.head_commit.message, 'deploy')
        run: echo "The commit message contains 'deploy'."
