name: Success and Failure Example

on:
  push:
    branches:
      - main

jobs:
  success-failure-example:
    runs-on: self-hosted
    steps:
      - name: Step 1
        run: jq

      - name: Step 2 - Success Condition
        if: success()
        run: echo "JQ is already installed"

      - name: Step 3 - Failure Condition
        if: failure()
        run: |
          sudo apt install -y jq
          echo "JQ is not their. So Installing NOW!!!"
